// Code generated by mockery v2.20.0. DO NOT EDIT.

package handlers

import mock "github.com/stretchr/testify/mock"

// StatusMessageError is an autogenerated mock type for the StatusMessageError type
type StatusMessageError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *StatusMessageError) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Message provides a mock function with given fields:
func (_m *StatusMessageError) Message() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Status provides a mock function with given fields:
func (_m *StatusMessageError) Status() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewStatusMessageError interface {
	mock.TestingT
	Cleanup(func())
}

// NewStatusMessageError creates a new instance of StatusMessageError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStatusMessageError(t mockConstructorTestingTNewStatusMessageError) *StatusMessageError {
	mock := &StatusMessageError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
